export default {
    home:{
        title:'We crafts experiences for your digital needs.',
        Project:[
            {
                id:1,
                title:'Àshworks',
                link:'https://ash-works.co/',
                imgUrl:'/image/projects/ashworks.png',
                imgSmallUrl:'http://api.dignite.studio/images/image/projects/ash-work-small.png',
                Category:'Web Development',
                landingImg: '/image/landingpage/ashwork.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/ashwork-small.jpg',
                carouselImg: ['/image/carousel/ashworks/ashwork-slider-satu.png','/image/carousel/ashworks/ashwork-slider-dua.png','/image/carousel/ashworks/ashwork-slider-tiga.png'],
                fullImg:'/image/full/ashwork.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/ashworks.png',
                slug:'ash-works',
                clientName:'Cassandra Louise',
                about:'Created by two ignited and passionate artists, aimed to bring positivity to the lives they touch, Àshworks is simply the effect of their volcanic burn. Inspired by the exterior of the world’s ecosphere, they combined their artful expertise to inspirit the interiors of your home’s atmosphere.',
                challenge:'Àshworks needed an e-commerce website that speaks through the heart of their customers. The site should be able to reflect their products that is focusing specifically on colour, mood, aura and space.',
                solution:'To complete their minimalist, classy design, we utilized seamless integration between company profile and e-commerce system with minimal motions to offer their visitors an effortless, fast, reliable website to explore and shop with.'
            },
            {
                id:2,
                title:'Spotless',
                link:'https://www.spotless.co.id/',
                imgUrl:'/image/projects/spotless.png',
                imgSmallUrl:'http://api.dignite.studio/images/image/projects/ash-work-small.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/spotless.png',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/spotless-small.jpg',
                carouselImg: ['/image/carousel/spotless/spotless-slider-satu.png','/image/carousel/spotless/spotless-slider-dua.png','/image/carousel/spotless/spotless-slider-tiga.png'],
                fullImg:'/image/full/spotless.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/spotless.png' ,
                slug:'spotless',
                clientName:'Prabadika H.',
                about:'Spotless is a company that offers shoe cleaning services as well as a variety of shoe care products. They believe that shoes have become an important element of visual self-representation and the most sought out fashion items for these past few years.',
                challenge:'The team came to us to seek a company website that aligns to their customers’ youthful, free-spirited character. It should be user-friendly and pleasing to the eye of their middle-class target market.',
                solution:'To answer their request, we created a dynamic and bold tone for the whole site. The site is also animation-rich so that customers can get the best experience while browsing their favourite shoe cleaning products.'
            },
            {
                id:3,
                title:'True Magic',
                link:'false',
                imgUrl:'/image/projects/truemagic.png',
                Category:'UI/UX',
                landingImg: '/image/landingpage/truemagic.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/truemagic-small.jpg',
                carouselImg: ['/image/carousel/truemagic/truemagic-slider-satu.png','/image/carousel/truemagic/truemagic-slider-dua.png','/image/carousel/truemagic-slider-tiga.png'],
                fullImg:'/image/full/truemagic.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/truemagic.png' ,
                slug:'truemagic',
                clientName:'Joshua Susanto',
                about:'Since it was founded in 2008, True Magic has a commitment to provide the best quality magic tools at affordable prices. As the tagline says, “Toko Alat Sulap dan Trik Sulap No. 1 di Indonesia”, their goal is only one: being able to facilitate their customers in learning the art of magic.',
                challenge:'The company wants to have a website design that can guide its customers to better understand the brand before buying the products. They should beforehand grasp the story, the why, and each of the product categories prior purchasing.',
                solution:'To answer this challenge, we designed a website layout that explicitly presents True Magic highlights on the homepage consecutively, depending on its objective. With an understandable headers, banners and notices, the interface is able to give a better visitor experience in a more hassle-free way.'
            },
            {
                id:4,
                title:'REYD',
                link:'https://reyd.co.id/',
                imgUrl:'/image/projects/reyd.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/reyd.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/reyd-small.jpg',
                carouselImg: ['/image/carousel/reyd/reyd-slider-satu.png','/image/carousel/reyd/reyd-slider-dua.png','/image/carousel/reyd/reyd-slider-tiga.png'],
                fullImg:'/image/full/reyd.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/reyd.png' ,
                slug:'reyd',
                clientName:'Alif Putera',
                about:'REYD is a company engaged in muslim sports apparel. The initial inspiration for this brand was the problem faced by muslim women who do not exercise because of hijab. This motivated REYD to become muslim women’s sports clothing solutions.',
                challenge:'The team wanted an e-commerce website that can adapt quickly to the changing of their apparel series. It should also be minimal yet still supports the basic commerce functions.',
                solution:'We created a commerce website that is clean and seamless with a monochrome tone and reducing the unnecessary on the pages for better adaptability. The site is also equipped with the ability to create promo code and shipping tracker for both shop manager and customers’ conveniences.'
            },
            {
                id:5,
                title:'Kumiusik',
                link:'http://www.kumiusik.id/',
                imgUrl:'/image/projects/kumiusik.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/kumiusik.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/kumiusik-small.jpg',
                carouselImg: ['/image/carousel/kumiusik/kumiusik-slider-satu.png','/image/carousel/kumiusik/kumiusik-slider-dua.png','/image/carousel/kumiusik/kumiusik-slider-tiga.png'],
                fullImg:'/image/full/kumiusik.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/kumiusik.png' ,
                slug:'kumiusik',
                clientName:'Febrian Adi',
                about:'Envisioned as the biggest indie-music source in Indonesia, Kumiusik is a music blog run by a passionate indie devotee. His unique mission is to engage his readers to have some music intakes for their right brains.',
                challenge:'The owner of Kumiusik wanted us to redesign its whole blog site. From the unsystematic layout, the needs of added features, the lack of brand consistency, we were challenged to change all that by creating a new, user-friendly face on the site.',
                solution:'A blog should be able to keep the readers stay as long as possible. To meet this requirement, we categorized everything from the navigation menu, article categories, widgets to footer contents. With a touch of black-and-red color scheme, the blog is now running blazingly for their indie-music enthusiasts.'
            },
            // {
            //     id:6,
            //     title:'Card Story',
            //     link:'false',
            //     imgUrl:'/image/projects/card-story.png',
            //     Category:'UI/UX',
            //     landingImg: '/image/landingpage/cardstory.png',
            //     landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/cardstory-small.png',
            //     carouselImg: ['/image/carousel/cardstory/cardstory-slider-satu.png','/image/carousel/cardstory/cardstory-slider-dua.png','/image/carousel/cardstory/cardstory-slider-tiga.png'],
            //     fullImg:'/image/full/cardstory.png' ,
            //     thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/card-story.png' ,
            //     slug:'cardstory',
            //     clientName:'Joshua Susanto',
            //     about:'Card Story is the largest premium playing cards store in Indonesia. They already served more than 2,500 satisfied customers and believe that this number will continue to grow.',
            //     challenge:'Premium brands ain’t simple. As our first client, the owner of Card Story asked us to make an interface design that can illustrate all the commerce functions and is able to portray their magical, premium brand persona.',
            //     solution:'In order to balance the needs, we created a website interface that is able to offer an experience for people who visit as both visitors and customers. With a dark-champagne tone, classic-modern font choices and rather static layout, the site is ready to run with a magic touch. '
            // },
            {
                id:6,
                title:'Prosper Kapital Ventura',
                link:'https://www.prosperventura.com',
                imgUrl:'/image/projects/front-prosper-min.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/mockup-prosper-min.png',
                landingSmallImg: 'https://api.dignite.studio/images/image/landingpage/cardstory-small.png',
                carouselImg: ['/image/carousel/prosper/prosper-slider-satu.png','/image/carousel/prosper/prosper-slider-dua.png','/image/carousel/prosper/prosper-slider-tiga.png'],
                fullImg:'/image/full/full-prosper-min.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/card-story.png' ,
                slug:'prosperventura',
                clientName:'Joshua Susanto',
                about:'Prosper Ventura is an analytical based financial services firm specializing in foreign exchange based asset management, and controlled risk capital investments. Managing an extensively growing investment portfolio, Prosper Ventura prides in providing a clear consulting service, with the aim of a definite growth of value for its clients.',
                challenge:'As a consulting and financial firm, the team requested a website that would be able to portray the credibility and professional image of their expertises. They also needed a system that would enable them to collect all clients’ registration data.',
                solution:'A corporate-look web interface with simple layout is the solution to suit their main target market, which revolves around business people. We also equipped the site with a registration system to smoothen the investment process.'
            },
        ],
        ProjectAll:[
            {
                id:1,
                title:'Àshworks',
                link:'https://ash-works.co/',
                imgUrl:'/image/projects/ashworks.png',
                imgSmallUrl:'http://api.dignite.studio/images/image/projects/ash-work-small.png',
                Category:'Web Development',
                landingImg: '/image/landingpage/ashwork.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/ashwork-small.jpg',
                carouselImg: ['/image/carousel/ashworks/ashwork-slider-satu.png','/image/carousel/ashworks/ashwork-slider-dua.png','/image/carousel/ashworks/ashwork-slider-tiga.png'],
                fullImg:'/image/full/ashwork.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/ashworks.png',
                slug:'ash-works',
                clientName:'Cassandra Louise',
                about:'Created by two ignited and passionate artists, aimed to bring positivity to the lives they touch, Àshworks is simply the effect of their volcanic burn. Inspired by the exterior of the world’s ecosphere, they combined their artful expertise to inspirit the interiors of your home’s atmosphere.',
                challenge:'Àshworks needed an e-commerce website that speaks through the heart of their customers. The site should be able to reflect their products that is focusing specifically on colour, mood, aura and space.',
                solution:'To complete their minimalist, classy design, we utilized seamless integration between company profile and e-commerce system with minimal motions to offer their visitors an effortless, fast, reliable website to explore and shop with.'
            },
            {
                id:2,
                title:'Spotless',
                link:'https://www.spotless.co.id/',
                imgUrl:'/image/projects/spotless.png',
                imgSmallUrl:'http://api.dignite.studio/images/image/projects/ash-work-small.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/spotless.png',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/spotless-small.jpg',
                carouselImg: ['/image/carousel/spotless/spotless-slider-satu.png','/image/carousel/spotless/spotless-slider-dua.png','/image/carousel/spotless/spotless-slider-tiga.png'],
                fullImg:'/image/full/spotless.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/spotless.png' ,
                slug:'spotless',
                clientName:'Prabadika H.',
                about:'Spotless is a company that offers shoe cleaning services as well as a variety of shoe care products. They believe that shoes have become an important element of visual self-representation and the most sought out fashion items for these past few years.',
                challenge:'The team came to us to seek a company website that aligns to their customers’ youthful, free-spirited character. It should be user-friendly and pleasing to the eye of their middle-class target market.',
                solution:'To answer their request, we created a dynamic and bold tone for the whole site. The site is also animation-rich so that customers can get the best experience while browsing their favourite shoe cleaning products.'
            },
            {
                id:3,
                title:'True Magic',
                link:'false',
                imgUrl:'/image/projects/truemagic.png',
                Category:'UI/UX',
                landingImg: '/image/landingpage/truemagic.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/truemagic-small.jpg',
                carouselImg: ['/image/carousel/truemagic/truemagic-slider-satu.png','/image/carousel/truemagic/truemagic-slider-dua.png','/image/carousel/truemagic-slider-tiga.png'],
                fullImg:'/image/full/truemagic.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/truemagic.png' ,
                slug:'truemagic',
                clientName:'Joshua Susanto',
                about:'Since it was founded in 2008, True Magic has a commitment to provide the best quality magic tools at affordable prices. As the tagline says, “Toko Alat Sulap dan Trik Sulap No. 1 di Indonesia”, their goal is only one: being able to facilitate their customers in learning the art of magic.',
                challenge:'The company wants to have a website design that can guide its customers to better understand the brand before buying the products. They should beforehand grasp the story, the why, and each of the product categories prior purchasing.',
                solution:'To answer this challenge, we designed a website layout that explicitly presents True Magic highlights on the homepage consecutively, depending on its objective. With an understandable headers, banners and notices, the interface is able to give a better visitor experience in a more hassle-free way.'
            },
            {
                id:4,
                title:'REYD',
                link:'https://reyd.co.id/',
                imgUrl:'/image/projects/reyd.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/reyd.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/reyd-small.jpg',
                carouselImg: ['/image/carousel/reyd/reyd-slider-satu.png','/image/carousel/reyd/reyd-slider-dua.png','/image/carousel/reyd/reyd-slider-tiga.png'],
                fullImg:'/image/full/reyd.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/reyd.png' ,
                slug:'reyd',
                clientName:'Alif Putera',
                about:'REYD is a company engaged in muslim sports apparel. The initial inspiration for this brand was the problem faced by muslim women who do not exercise because of hijab. This motivated REYD to become muslim women’s sports clothing solutions.',
                challenge:'The team wanted an e-commerce website that can adapt quickly to the changing of their apparel series. It should also be minimal yet still supports the basic commerce functions.',
                solution:'We created a commerce website that is clean and seamless with a monochrome tone and reducing the unnecessary on the pages for better adaptability. The site is also equipped with the ability to create promo code and shipping tracker for both shop manager and customers’ conveniences.'
            },
            {
                id:5,
                title:'Kumiusik',
                link:'http://www.kumiusik.id/',
                imgUrl:'/image/projects/kumiusik.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/kumiusik.jpg',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/kumiusik-small.jpg',
                carouselImg: ['/image/carousel/kumiusik/kumiusik-slider-satu.png','/image/carousel/kumiusik/kumiusik-slider-dua.png','/image/carousel/kumiusik/kumiusik-slider-tiga.png'],
                fullImg:'/image/full/kumiusik.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/kumiusik.png' ,
                slug:'kumiusik',
                clientName:'Febrian Adi',
                about:'Envisioned as the biggest indie-music source in Indonesia, Kumiusik is a music blog run by a passionate indie devotee. His unique mission is to engage his readers to have some music intakes for their right brains.',
                challenge:'The owner of Kumiusik wanted us to redesign its whole blog site. From the unsystematic layout, the needs of added features, the lack of brand consistency, we were challenged to change all that by creating a new, user-friendly face on the site.',
                solution:'A blog should be able to keep the readers stay as long as possible. To meet this requirement, we categorized everything from the navigation menu, article categories, widgets to footer contents. With a touch of black-and-red color scheme, the blog is now running blazingly for their indie-music enthusiasts.'
            },
            {
                id:6,
                title:'Card Story',
                link:'false',
                imgUrl:'/image/projects/card-story.png',
                Category:'UI/UX',
                landingImg: '/image/landingpage/cardstory.png',
                landingSmallImg: 'http://api.dignite.studio/images/image/landingpage/cardstory-small.png',
                carouselImg: ['/image/carousel/cardstory/cardstory-slider-satu.png','/image/carousel/cardstory/cardstory-slider-dua.png','/image/carousel/cardstory/cardstory-slider-tiga.png'],
                fullImg:'/image/full/cardstory.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/card-story.png' ,
                slug:'cardstory',
                clientName:'Joshua Susanto',
                about:'Card Story is the largest premium playing cards store in Indonesia. They already served more than 2,500 satisfied customers and believe that this number will continue to grow.',
                challenge:'Premium brands ain’t simple. As our first client, the owner of Card Story asked us to make an interface design that can illustrate all the commerce functions and is able to portray their magical, premium brand persona.',
                solution:'In order to balance the needs, we created a website interface that is able to offer an experience for people who visit as both visitors and customers. With a dark-champagne tone, classic-modern font choices and rather static layout, the site is ready to run with a magic touch. '
            },
            {
                id:7,
                title:'Prosper Kapital Ventura',
                link:'https://www.prosperventura.com',
                imgUrl:'/image/projects/front-prosper-min.png',
                Category:'Web Development and UI/UX',
                landingImg: '/image/landingpage/mockup-prosper-min.png',
                landingSmallImg: 'https://api.dignite.studio/images/image/landingpage/cardstory-small.png',
                carouselImg: ['/image/carousel/prosper/prosper-slider-satu.png','/image/carousel/cardstory/prosper-slider-dua.png','/image/carousel/cardstory/prosper-slider-tiga.png'],
                fullImg:'/image/full/full-prosper-min.png' ,
                thumbImg:'https://image-dignite.s3-ap-southeast-1.amazonaws.com/Projects/thumbnail/card-story.png' ,
                slug:'prosperventura',
                clientName:'Joshua Susanto',
                about:'Prosper Ventura is an analytical based financial services firm specializing in foreign exchange based asset management, and controlled risk capital investments. Managing an extensively growing investment portfolio, Prosper Ventura prides in providing a clear consulting service, with the aim of a definite growth of value for its clients.',
                challenge:'As a consulting and financial firm, the team requested a website that would be able to portray the credibility and professional image of their expertises. They also needed a system that would enable them to collect all clients’ registration data.',
                solution:'A corporate-look web interface with simple layout is the solution to suit their main target market, which revolves around business people. We also equipped the site with a registration system to smoothen the investment process.'
            },
        ]
    },
    about:{
        title:'We combine research, strategy and design to build digital products people like to engage with.',
        process: [
            {title:'Ask',description:"We start with a few simple questions. Through thoughtful consideration of your responses, we're able to craft the essential guidelines that will shape your brand's online experience."},
            {title:'Design',description:"We make data-driven decisions based on your story while innovating every step of the way. From mobile to tablet to full wall projections, our digital creations are designed to make an impact on any medium."},
            {title:'Develop',description:"Our people are artists - they can breathe life into designs and make digital products move in ways you never thought possible. The products and platforms we develop are modular, so they can easily evolve over time."},
            {title:'Support',description:"We're here to help you. Reach out to us anytime, for anything you need. Ongoing technical support is part of the deal, so you can focus on growing your business—worry-free."}
        ],
        do: ['Web & App Development','UX Design','Web Design','Graphic Design'],
        team: [
            {name:'Faikar Ghassan',job:'Full-Stack Developer',LinkPhoto:'http://api.dignite.studio/images/image/Faikar.jpg',alt:'phototeam1'},
            {name:'Mayesta Arientasta',job:'UI/UX Designer',LinkPhoto:'http://api.dignite.studio/images/image/Tasya.jpg',alt:'phototeam2'},
            {name:'Egi Muharram',job:'Graphic Designer',LinkPhoto:'http://api.dignite.studio/images/image/egi.jpg',alt:'phototeam3'}
        ]
    },
    work:{
        title:'We design and build high-end digital products for all kind of clients and audiences.'
    },
    footer:{
        get:'Get in touch',
        address: ['Jl. Raya Rawabuntu','Ruko Golden Vienna','Blok BB No.11 Lt.2','Serpong, Tangerang Selatan'],
        email:'hello@dignite.studio',
        phone:'(+62) 812 8783 1421'
    }
}


let data = ['Photo by Alvaro Reyes on Unsplash','Photo by Tran Mau Tri Tam on Unsplash','Photo by NeONBRAND on Unsplash','Photo by Le Buzz on Unsplash']